### ISSUE TITLE
[ Twig_Error_Syntax: The function "thumbnail" does not exist in "post" at line 9 ]

### ISSUE THREAD

**Issue by rmanniez** [beryllium/icelus#4]
Hello,

I followed your documentation but I have an error : 

`[ Twig_Error_Syntax: The function "thumbnail" does not exist in "post" at line 9 ]`

Line 9
`<a href="image.jpg"><img src="{{ thumbnail('image.jpg', 100, 100) }}"></a>`

I have the latest version of Sculpin, can be the source of the problem?

Thank

**Comment by beryllium** [comment]
Did you create the "app/SculpinKernel.php" file in the root of your sculpin project (not inside the "source/" folder)? I was able to get a local test working on a fresh Sculpin install, but before I created the SculpinKernel.php file, I was getting the same error you were getting.

**Comment by rmanniez** [comment]
Thank you I just found 5 minutes before your answer, in fact I had created the file but modified it in /app/config/

Thanks

**Comment by beryllium** [comment]
Ah, glad to hear it - if you can think of any features for Icelus, please feel free to add them as issues on the project. Thanks for trying it out!
